### ISSUE TITLE
New Incognito window + Dark Mode UI.

### ISSUE THREAD

**Issue by rereser** [IDA-RE-things/Chrome-xp-api-adapter#27] opened 2024-12-03 08:14 UTC
OS: Win XP SP3 ( no HW accell )
Browser: Supermium 126.0.6478.256 R5 + chrome-xpapi-adapter_x86.b5081-full.

New Incognito window has white background.
The flag: chrome://flags/#force-dark-mode does not work anymore.

**Comment by IDA-RE-things** [comment] 2024-12-03 10:59
I'm not using this features, so not checked them.
I have fixed seting of dark mode from `chrome://flags/#force-dark-mode` currently.
But for dinamically Incognito background changes, it should do CPU-intensive checks for incognito mode many times, if its not cached, as I have currently implemented..

To resolve such dilema, I think I will implement additional command-line parameter, which will disable such caching, allowing background color changes for incognito.

**Comment by rereser** [comment] 2024-12-03 13:15
Another issue found.
On the New Tab page, "Customize Supermium", the color can not be changed.

**Comment by IDA-RE-things** [comment] 2024-12-03 18:14
Have uploaded `chrome-xpapi-adapter.1.2.0.5082.beta.dll`
See release notes how to use it. And write if this works for you.

**Comment by Vangelis66** [comment] 2024-12-04 00:35
FTR, this appears to be a **WinXP_SP3**-_specific_ issue :wink: ; under **Windows Vista SP2 32-bit**, "full" build **v1081** works as intended :+1: ; I just checked (to make sure once more) and `chrome://flags/#force-dark-mode` works OK here (after a browser restart), `New Incognito Window` opens as _dark_ when the aforementioned flag has been previously _enabled_... Just as a FYI :smile: ...

**Comment by rereser** [comment] 2024-12-04 08:48
Tested chrome-xpapi-adapter.1.2.0.5082.beta.dll.
Everything now works as described in the release notes.

Note that i do not use the "dark mode" flag or the other two posted chrome options.
Just found these issues after running some tests on the new v1.2.0.5081 version.
So i would like to know what the performance drop is when using the switch.

**Comment by IDA-RE-things** [comment] 2024-12-04 10:42
Yes, this issue is only for WinXP, because its not implemented for Vista. :-) Vista dont allow me to patch Chrome.dll on-the fly and redirect to my replacement functions.  Althrough Win7 allow.
The performance drop not so high to feel with few tabs. You can fearlessly use it.

**Comment by rereser** [comment] 2024-12-04 12:43
Only use a few tabs at a time so will run Supermium with the switch.
Thank you for your continuous efforts.

**Comment by rereser** [comment] 2024-12-17 09:37
Supermium 126.0.6478.260 R6 + chrome-xpapi-adapter_x86.b5082-full
No more need for using the switch --disable-widget-color-caching.
"New Incognito window" and "Cusomize Supermium" now display and function as intended.

**Comment by IDA-RE-things** [comment] 2024-12-17 11:21
Its because this features not implemented for R6 -)), only for R3,R4,R5 yet. So no side effects for R6. Have not seen new R6 version yet. Will be in near future.

**Closed as completed** 2024-12-17 12:43 UTC
Labels: fixed/resolved
