### ISSUE TITLE
discord issue with v1.2.0.5036

### ISSUE THREAD

**Issue by rereser** [IDA-RE-things/Chrome-xp-api-adapter#7] opened 2024-05-10 06:36 UTC
discord "aw snap" crash.
to reproduce in supermium r4 on win xp sp3.
go to https://legacyupdate.net/
click the community discord link and accept the invite.
with version 1.2.0.5036 the page will crash.
with version 1.2.0.5035 it does not.

**Comment by IDA-RE-things** [comment] 2024-05-10 06:58
Hmm.... Ok. thanks for testing.
Will check whats happened.
I will disable downloads in such case while. While I'm' have not fixed this.

**Comment by IDA-RE-things** [comment] 2024-05-10 07:21
BTW, is it created any crashdumps (*.dmp) under "Supermium_UserData\Crashpad\reports\" ?
I can't reproduce while.

**Comment by rereser** [comment] 2024-05-10 07:32
yes, where to upload?

**Comment by rereser** [comment] 2024-05-10 07:35
yes.
[Uploading e1597f3a-f6e2-456e-b9fa-c1319c3c0409.dmp…]()

**Comment by IDA-RE-things** [comment] 2024-05-10 07:35
k. will look..

**Comment by IDA-RE-things** [comment] 2024-05-10 07:39
Its should be able to attach this .dmp as attachnent.
I still can't reproduce this, because having no discrod and discord account. It works on other sites for me.
Need a crashdump.

**Comment by rereser** [comment] 2024-05-10 07:50
[e1597f3a-f6e2-456e-b9fa-c1319c3c0409.dmp](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/files/15271923/e1597f3a-f6e2-456e-b9fa-c1319c3c0409.dmp)

**Comment by rereser** [comment] 2024-05-10 07:59
another thing i noticed.
with v1.2.0.5035 the bookmark i have to a discord channel is a blue circle with a red dot.
that red dot will change to numbers if there are unread messages.
with v 1.2.0.5036 that bookmark icon is missing the red dot.
don't know if this helps, have limited knowledge how discord and github work.
you will need to register on discord to reproduce i think.

**Comment by rereser** [comment] 2024-05-10 08:15
same problem with v1.2.0.5037.
[9f2ec091-1a12-45cc-8663-c45990995821.dmp](https://github.com/IDA-RE-things/Chrome-xp-api-adapter/files/15272202/9f2ec091-1a12-45cc-8663-c45990995821.dmp)

**Comment by IDA-RE-things** [comment] 2024-05-10 08:26
Try build 5038. Should be fixed now. Also the problem with bookmark color may be fixed.

**Comment by rereser** [comment] 2024-05-10 08:40
v1.2.0.5038 fixed the issue.
discord bookmark icon with the red dot is also good now.
thank you for your amazing work and the fast response.
this dll makes a huge difference in supermium r4 load time.
it also seems to resolve the frequently hanging chrome processes on browser exit with the default supermium 1.1.0.5010 dll.

**Comment by IDA-RE-things** [comment] 2024-05-10 09:11
the buid 5039 has more fine-tuning, done by optimizer. You can use what you want. No other changes made.

**Comment by rereser** [comment] 2024-05-10 09:21
thanks again.
will use v1.2.0.5039 for now.
issue closed.

**Closed** 2024-05-10 09:21 UTC
